import './App.css';
import { useState } from 'react';
import axios from 'axios';
import Header from './components/Header';

function App() {
  const [userName, setUserName] = useState('');
  const [data, setData] = useState({
    person: {
      professionalHeadline:
        'Full-stack Web developer | Helping companies modernize their online presence with full-stack web development services. | Ruby on Rails, Web Development, React.',
      completion: 0.8235,
      showPhone: false,
      created: '2023-03-30T12:18:09Z',
      verified: false,
      flags: {
        accessCohort: false,
        benefits: false,
        canary: false,
        enlauSource: false,
        fake: false,
        featureDiscovery: true,
        firstSignalSent: false,
        signalsOnboardingCompleted: false,
        importingLinkedin: true,
        onBoarded: true,
        remoter: true,
        signalsFeatureDiscovery: true,
        importingLinkedinRecommendations: false,
        contactsImported: true,
        appContactsImported: false,
        genomeCompletionAcknowledged: false,
        cvImported: true,
        communityCreatedPrivate: false,
        communityCreatedClaimed: false,
        connectBenefitsViewed: true,
        recommendationLeadEmailSent: false,
        recommendationsAskedGenomeCompletion: false,
        behavioralTraitsAcknowledged: false,
        testTaken: false,
        previewFeatureDiscovery: true,
        boosted: false,
      },
      weight: 0,
      ggId: '1486288',
      completionStage: {
        stage: 3,
        progress: 0.4,
      },
      locale: 'en',
      subjectId: 1486288,
      picture:
        'https://res.cloudinary.com/torre-technologies-co/image/upload/v1680179434/origin/starrgate/users/profile_c526cc7cd8f2dfb673cf66ab5fd382e84539f032.jpg',
      hasEmail: true,
      isTest: false,
      name: 'Wander Alberto González Martínez',
      links: [
        {
          id: 'nM44loGM',
          name: 'linkedin',
          address: 'https://www.linkedin.com/in/wander-gonzalez/',
        },
      ],
      location: {
        name: 'Nacional, Dominican Republic',
        shortName: 'Nacional, Dominican Republic',
        country: 'Dominican Republic',
        latitude: 18.4649,
        longitude: -69.8865,
        timezone: 'America/Santo_Domingo',
        timezoneOffSet: -14400000,
      },
      theme: 'deepOrange500',
      id: 'vy52nQ1N',
      pictureThumbnail:
        'https://res.cloudinary.com/torre-technologies-co/image/upload/c_fill,h_150,w_150/v1680179434/origin/starrgate/users/profile_c526cc7cd8f2dfb673cf66ab5fd382e84539f032.jpg',
      claimant: false,
      summaryOfBio:
        'As an experienced Full-Stack Developer with expertise in React, Redux, and JavaScript, I have a strong focus on creating visually appealing and functional web applications. I excel both independently and as part of a team, leveraging remote work and pair programming to deliver high-quality projects. With keen attention to visual detail, I possess the ability to plan, design, and implement software applications, components, and interfaces, as well as conduct thorough pull request reviews. I am a proficient Git user and have demonstrated rapid adaptability to new technologies. Additionally, I am an effective communicator and collaborator with extensive experience working in agile Kanban environments.',
      publicId: 'wandergonzalez0',
    },
    stats: {
      jobs: 3,
      projects: 1,
      education: 4,
      strengths: 45,
    },
    strengths: [
      {
        id: 'jl73boqM',
        code: 62230,
        name: 'Time management',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:55',
        hits: 17637,
      },
      {
        id: 'M97LgRzy',
        code: 37555,
        name: 'Algorithms',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:40',
        hits: 4029,
      },
      {
        id: 'MBkeaOXj',
        code: 74268,
        name: 'Cascading Style Sheets (CSS)',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:33',
        hits: 42,
      },
      {
        id: 'NVxZ2g8j',
        code: 247437,
        name: 'Resiliency',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:24',
        hits: 3,
      },
      {
        id: 'yoBqOodj',
        code: 84421,
        name: 'Back-End Web Development',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:19',
        hits: 22,
      },
      {
        id: 'MR8o0p5y',
        code: 6086261,
        name: 'Vehicle maintenance',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:06',
        hits: 41,
      },
      {
        id: 'y1QzWdKy',
        code: 5537,
        name: 'Mechanics',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T17:00:00',
        hits: 388,
      },
      {
        id: 'ybd4b79M',
        code: 473965,
        name: 'Gitflow',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:52',
        hits: 1350,
      },
      {
        id: 'jrDWbo0N',
        code: 34500,
        name: 'Scrum',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:45',
        hits: 118653,
      },
      {
        id: 'Na2wJKoM',
        code: 5284,
        name: 'Kanban',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:39',
        hits: 2397,
      },
      {
        id: 'y5aKERby',
        code: 1272231,
        name: 'Responsive web design',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:32',
        hits: 724,
      },
      {
        id: 'MLnEW9by',
        code: 306306,
        name: 'Material ui',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:24',
        hits: 855,
      },
      {
        id: 'j64wEVQN',
        code: 45396,
        name: 'Leadership',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:19',
        hits: 494868,
      },
      {
        id: 'M26DER2M',
        code: 9065494,
        name: 'Easily Adaptable',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:15',
        hits: 0,
      },
      {
        id: 'yQx1PAnj',
        code: 82497,
        name: 'Technical writing',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:08',
        hits: 892,
      },
      {
        id: 'MEvgXo1j',
        code: 59725,
        name: 'Project management',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:59:03',
        hits: 385707,
      },
      {
        id: 'M7Y4dRxy',
        code: 15369144,
        name: 'Prioritize Workload',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:58:55',
        hits: 0,
      },
      {
        id: 'NKn7gRoy',
        code: 1714,
        name: 'Interpersonal Skills',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:58:48',
        hits: 2469,
      },
      {
        id: 'yY3v8z2M',
        code: 33391,
        name: 'Collaboration',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-04-01T16:58:30',
        hits: 732,
      },
      {
        id: 'y0l1v9Ky',
        code: 55799,
        name: 'MySQL',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-31T00:35:51',
        hits: 81477,
      },
      {
        id: 'M97ZPpOy',
        code: 37842,
        name: 'API management',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-31T00:32:32',
        hits: 559,
      },
      {
        id: 'Mq0DJlpN',
        code: 235856,
        name: 'Git',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T13:07:16',
        hits: 316785,
      },
      {
        id: 'Mv9xWEON',
        code: 55521,
        name: 'Front-end development',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T13:07:14',
        hits: 13873,
      },
      {
        id: 'M26oPk2M',
        code: 23802,
        name: 'HTML',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T13:04:32',
        hits: 167269,
      },
      {
        id: 'M4JVYOky',
        code: 23009,
        name: 'CSS',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T13:04:30',
        hits: 140939,
      },
      {
        id: 'jAWJak1N',
        code: 489426,
        name: 'REST API',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:58:01',
        hits: 1771,
      },
      {
        id: 'N8Ol7P7y',
        code: 55909,
        name: 'Jest',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:57:28',
        hits: 3674,
      },
      {
        id: 'yJnYAXEy',
        code: 50289,
        name: 'Redux',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:57:23',
        hits: 11747,
      },
      {
        id: 'jpXWqAJj',
        code: 23818,
        name: 'React.js',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:57:18',
        hits: 40220,
      },
      {
        id: 'yna8kZ3j',
        code: 18523,
        name: 'RSpec',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:45:38',
        hits: 362,
      },
      {
        id: 'ybdlLX1M',
        code: 49214,
        name: 'PostgreSQL',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:45:30',
        hits: 50998,
      },
      {
        id: 'M26oPvAM',
        code: 1939128,
        name: 'CRUD',
        proficiency: 'novice',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:45:14',
        hits: 14,
      },
      {
        id: 'Mv9xWaPN',
        code: 46139,
        name: 'Mechatronics',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:43:04',
        hits: 1215,
      },
      {
        id: 'NmDXAl7y',
        code: 55795,
        name: 'Management',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:43:04',
        hits: 606633,
      },
      {
        id: 'Mezmr3ej',
        code: 20923,
        name: 'Design',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:43:04',
        hits: 427797,
      },
      {
        id: 'jAWJaYZN',
        code: 59477,
        name: 'JavaScript',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:43:04',
        hits: 281742,
      },
      {
        id: 'jpXWql7j',
        code: 431480,
        name: 'Remote',
        proficiency: 'expert',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:43:04',
        hits: 7026,
      },
      {
        id: 'y0l1WAwy',
        code: 29411,
        name: 'Ruby on Rails',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:44:51',
        hits: 22199,
      },
      {
        id: 'MLnxvD9y',
        code: 287426,
        name: 'Full-stack development',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:49',
        hits: 6116,
      },
      {
        id: 'j649xvrN',
        code: 49033,
        name: 'Play Framework',
        proficiency: 'no-experience-interested',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:44',
        hits: 498,
      },
      {
        id: 'M26oPXLM',
        code: 56891,
        name: 'Website development',
        proficiency: 'proficient',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:37',
        hits: 91138,
      },
      {
        id: 'yQx48Xmj',
        code: 32590,
        name: 'TypeScript',
        proficiency: 'no-experience-interested',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:27',
        hits: 76922,
      },
      {
        id: 'M4JVYzxy',
        code: 425235,
        name: 'Nuxt.js',
        proficiency: 'no-experience-interested',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:23',
        hits: 1024,
      },
      {
        id: 'jwrKDb2M',
        code: 32059,
        name: 'Scala',
        proficiency: 'no-experience-interested',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:20',
        hits: 4066,
      },
      {
        id: 'Nx67P9gj',
        code: 23826,
        name: 'Vue.js',
        proficiency: 'no-experience-interested',
        weight: 0,
        recommendations: 0,
        media: [],
        supra: false,
        created: '2023-03-30T12:21:16',
        hits: 21559,
      },
    ],
    interests: [],
    experiences: [
      {
        id: 'mjlRa3DN',
        category: 'jobs',
        name: 'Web development intern',
        organizations: [
          {
            id: 1446712,
            name: 'Syntonex',
            publicId: 'Syntonex',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'Developed and implemented new features that increased user engagement and retention.',
          "Built a JavaScript-based feature that addressed users' concerns about app navigation and improved user experience.",
          'Implemented a responsive design using HTML and CSS that improved the user experience on mobile devices and increased mobile traffic.',
        ],
        fromMonth: 'October',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        remote: false,
        additionalInfo:
          "Web development internship for a school data management website service in a startup company using PHP, JS, CSS, and HTML. \n●Developed and implemented new features that increased user engagement and retention. \n●Built a JavaScript-based feature that addressed users' concerns about app navigation and improved user experience. \n●Implemented a responsive design using HTML and CSS that improved the user experience on mobile devices and increased mobile trafic. \n●Developed and implemented new features that improved the user interface and usability, resulting in a decrease in bounce rate and an increase in user satisfaction. \n●Improved team performance by suggesting best practices and implementing code best practices, resulting in an increase in code maintainability and a reduction in development time. ",
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'XMqRO49j',
        category: 'projects',
        name: 'EV renting app',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'March',
        fromYear: '2022',
        toMonth: 'January',
        toYear: '2023',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'eynRmWEy',
        category: 'jobs',
        name: 'Full Stack Web Developer',
        organizations: [
          {
            id: 848840,
            name: 'Highlighted Personal Projects',
            publicId: 'HighlightedPersonalProjects',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'EV renting app (Team project) — Full-Stack web app, to manage CRUD operations in an electric car renting for test drive website. Complete Authorization, and authentication of users. CRUD operations on vehicles and Reservations.',
          'Budget App (Personal project) — Created a mobile/web application where users can manage their budget, with a list of transactions associated with a category, so that users can manage their expenses.',
          'Recipe App (Team project) — The Recipe App keeps track of all our recipes, ingredients, and inventory.',
        ],
        fromMonth: 'April',
        fromYear: '2022',
        toMonth: 'January',
        toYear: '2023',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'xM9v9bAj',
        category: 'education',
        name: 'Microverse Software Development Program',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'February',
        fromYear: '2023',
        toMonth: 'February',
        toYear: '2023',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'pydRlLGM',
        category: 'education',
        name: 'Remote Full Stack Web Development Program,',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'March',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 2,
        strengths: [],
      },
      {
        id: 'pyoReDej',
        category: 'jobs',
        name: 'Automotive service Mechanic',
        organizations: [
          {
            id: 1082170,
            name: 'Grupo Cometa',
            publicId: 'GrupoCometa',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'High-school Technician internship for mechanical apprentice.',
        ],
        fromMonth: 'April',
        fromYear: '2019',
        toMonth: 'September',
        toYear: '2019',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 3,
        strengths: [],
      },
      {
        id: '9MBPmp8y',
        category: 'education',
        name: 'Microverse Ruby on Rails Module',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'December',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 3,
        strengths: [],
      },
      {
        id: '5ykRwd2j',
        category: 'education',
        name: 'Technician in Mechatronics',
        organizations: [
          {
            id: 888421,
            name: 'Las Americas Institute of Technology',
            publicId: 'LasAmericasInstituteOfTechnology',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'April',
        fromYear: '2019',
        toMonth: 'December',
        toYear: '2021',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 4,
        strengths: [],
      },
    ],
    awards: [],
    jobs: [
      {
        id: 'mjlRa3DN',
        category: 'jobs',
        name: 'Web development intern',
        organizations: [
          {
            id: 1446712,
            name: 'Syntonex',
            publicId: 'Syntonex',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'Developed and implemented new features that increased user engagement and retention.',
          "Built a JavaScript-based feature that addressed users' concerns about app navigation and improved user experience.",
          'Implemented a responsive design using HTML and CSS that improved the user experience on mobile devices and increased mobile traffic.',
        ],
        fromMonth: 'October',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        remote: false,
        additionalInfo:
          "Web development internship for a school data management website service in a startup company using PHP, JS, CSS, and HTML. \n●Developed and implemented new features that increased user engagement and retention. \n●Built a JavaScript-based feature that addressed users' concerns about app navigation and improved user experience. \n●Implemented a responsive design using HTML and CSS that improved the user experience on mobile devices and increased mobile trafic. \n●Developed and implemented new features that improved the user interface and usability, resulting in a decrease in bounce rate and an increase in user satisfaction. \n●Improved team performance by suggesting best practices and implementing code best practices, resulting in an increase in code maintainability and a reduction in development time. ",
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'eynRmWEy',
        category: 'jobs',
        name: 'Full Stack Web Developer',
        organizations: [
          {
            id: 848840,
            name: 'Highlighted Personal Projects',
            publicId: 'HighlightedPersonalProjects',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'EV renting app (Team project) — Full-Stack web app, to manage CRUD operations in an electric car renting for test drive website. Complete Authorization, and authentication of users. CRUD operations on vehicles and Reservations.',
          'Budget App (Personal project) — Created a mobile/web application where users can manage their budget, with a list of transactions associated with a category, so that users can manage their expenses.',
          'Recipe App (Team project) — The Recipe App keeps track of all our recipes, ingredients, and inventory.',
        ],
        fromMonth: 'April',
        fromYear: '2022',
        toMonth: 'January',
        toYear: '2023',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'pyoReDej',
        category: 'jobs',
        name: 'Automotive service Mechanic',
        organizations: [
          {
            id: 1082170,
            name: 'Grupo Cometa',
            publicId: 'GrupoCometa',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [
          'High-school Technician internship for mechanical apprentice.',
        ],
        fromMonth: 'April',
        fromYear: '2019',
        toMonth: 'September',
        toYear: '2019',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 3,
        strengths: [],
      },
    ],
    projects: [
      {
        id: 'XMqRO49j',
        category: 'projects',
        name: 'EV renting app',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'March',
        fromYear: '2022',
        toMonth: 'January',
        toYear: '2023',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
    ],
    publications: [],
    education: [
      {
        id: 'xM9v9bAj',
        category: 'education',
        name: 'Microverse Software Development Program',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'February',
        fromYear: '2023',
        toMonth: 'February',
        toYear: '2023',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 1,
        strengths: [],
      },
      {
        id: 'pydRlLGM',
        category: 'education',
        name: 'Remote Full Stack Web Development Program,',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'March',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 2,
        strengths: [],
      },
      {
        id: '9MBPmp8y',
        category: 'education',
        name: 'Microverse Ruby on Rails Module',
        organizations: [
          {
            id: 122906,
            name: 'Microverse',
            publicId: 'Microverse',
            picture:
              'https://res.cloudinary.com/torre-technologies-co/image/upload/v1600908120/origin/bio/organizations/Microverse_mve5lx.png',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'December',
        fromYear: '2022',
        toMonth: 'December',
        toYear: '2022',
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 3,
        strengths: [],
      },
      {
        id: '5ykRwd2j',
        category: 'education',
        name: 'Technician in Mechatronics',
        organizations: [
          {
            id: 888421,
            name: 'Las Americas Institute of Technology',
            publicId: 'LasAmericasInstituteOfTechnology',
            serviceType: 'self_service',
          },
        ],
        responsibilities: [],
        fromMonth: 'April',
        fromYear: '2019',
        toMonth: 'December',
        toYear: '2021',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
        rank: 4,
        strengths: [],
      },
    ],
    opportunities: [
      {
        id: 'ydOxQLpj',
        interest: 'hiring',
        field: 'active',
        data: false,
      },
      {
        id: 'yzKmvzoN',
        interest: 'jobs',
        field: 'desirable-compensation-currency',
        data: 'USD$',
      },
      {
        id: 'MWov3gzM',
        interest: 'jobs',
        field: 'desirable-compensation-periodicity',
        data: 'monthly',
      },
      {
        id: 'yD72z9zj',
        interest: 'jobs',
        field: 'desirable-compensation-amount',
        data: 1500,
      },
      {
        id: 'NPDB4wAN',
        interest: 'jobs',
        field: 'desirable-compensation-publicly-visible',
        data: true,
      },
    ],
    languages: [
      {
        code: 'es',
        language: 'Spanish',
        fluency: 'fully-fluent',
      },
      {
        code: 'en',
        language: 'English',
        fluency: 'conversational',
      },
    ],
  });

  const fetchUserData = async () => {
    // const response = await axios.get(`https://torre.bio/api/bios/${userName}`);
    // setData(response.data);
  };

  const proficiencies = [
    'master',
    'expert',
    'proficient',
    'beginner',
    'no-experience-interested',
  ];

  return (
    <div className="App">
      <Header setUserName={setUserName} fetchUserData={fetchUserData} />
      {data && (
        <div className="px-3">
          <img src={data.person.picture} alt="Profile" />
          <h3 className="text-center mt-5 heading-1">{data.person.name}</h3>
          <div className="my-5">
            <h4 className="heading-2 my-4">Skills and interests:</h4>
            {proficiencies.map((categorie) => (
              <div key={Math.random()}>
                <h5 className="heading-3 my-3">
                  {categorie !== 'no-experience-interested'
                    ? categorie.charAt(0).toUpperCase() + categorie.slice(1)
                    : 'No experience but interested'}
                </h5>
                <ul>
                  {data.strengths.map((element) => {
                    if (element.proficiency === categorie) {
                      return <li key={Math.random()}>{element.name}</li>;
                    }
                    return null;
                  })}
                </ul>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default App;
